package com.myspace.ublaccountopening;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class savings_account_object implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "SAVINGS_ACCOUNT_OBJECT_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "SAVINGS_ACCOUNT_OBJECT_ID_SEQ", name = "SAVINGS_ACCOUNT_OBJECT_ID_GENERATOR")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Client Name")
	private java.lang.String clientName;

	@org.kie.api.definition.type.Label("CIF Number")
	private java.lang.String clientNo;

	@org.kie.api.definition.type.Label("Date Request Created")
	private java.util.Date requestDate;

	@org.kie.api.definition.type.Label("Name of the Branch")
	private java.lang.String branchName;

	@org.kie.api.definition.type.Label("Account N/o")
	private java.lang.String accountNo;

	@org.kie.api.definition.type.Label("Email")
	private java.lang.String email;

	@org.kie.api.definition.type.Label("Phone Number")
	private java.lang.String phoneNumber;

	@org.kie.api.definition.type.Label("Branch Code")
	private java.lang.String branchCode;

	@org.kie.api.definition.type.Label(value = "Decision")
	private java.lang.String decision;

	public savings_account_object() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getClientName() {
		return this.clientName;
	}

	public void setClientName(java.lang.String clientName) {
		this.clientName = clientName;
	}

	public java.lang.String getClientNo() {
		return this.clientNo;
	}

	public void setClientNo(java.lang.String clientNo) {
		this.clientNo = clientNo;
	}

	public java.util.Date getRequestDate() {
		return this.requestDate;
	}

	public void setRequestDate(java.util.Date requestDate) {
		this.requestDate = requestDate;
	}

	public java.lang.String getBranchName() {
		return this.branchName;
	}

	public void setBranchName(java.lang.String branchName) {
		this.branchName = branchName;
	}

	public java.lang.String getAccountNo() {
		return this.accountNo;
	}

	public void setAccountNo(java.lang.String accountNo) {
		this.accountNo = accountNo;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(java.lang.String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public java.lang.String getBranchCode() {
		return this.branchCode;
	}

	public void setBranchCode(java.lang.String branchCode) {
		this.branchCode = branchCode;
	}

	public java.lang.String getDecision() {
		return this.decision;
	}

	public void setDecision(java.lang.String decision) {
		this.decision = decision;
	}

	public savings_account_object(java.lang.Long id,
			java.lang.String clientName, java.lang.String clientNo,
			java.util.Date requestDate, java.lang.String branchName,
			java.lang.String accountNo, java.lang.String email,
			java.lang.String phoneNumber, java.lang.String branchCode,
			java.lang.String decision) {
		this.id = id;
		this.clientName = clientName;
		this.clientNo = clientNo;
		this.requestDate = requestDate;
		this.branchName = branchName;
		this.accountNo = accountNo;
		this.email = email;
		this.phoneNumber = phoneNumber;
		this.branchCode = branchCode;
		this.decision = decision;
	}

}